"""Add cascade delete shelf

Revision ID: 79fc84cf97e9
Revises: e736d3d3c594
Create Date: 2026-07-09 23:19:14.133266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '79fc84cf97e9'
down_revision: Union[str, Sequence[str], None] = 'e736d3d3c594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shelves_store_id_fkey'), 'shelves', type_='foreignkey')
    op.create_foreign_key(None, 'shelves', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelves', type_='foreignkey')
    op.create_foreign_key(op.f('shelves_store_id_fkey'), 'shelves', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###
