from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, field_validator


class DashboardSummaryResponse(BaseModel):
    """Aggregated real-time metrics for executive store dashboard."""

    model_config = ConfigDict(
        from_attributes=True,
        frozen=True,
    )

    current_visitors: int = Field(
        ...,
        ge=0,
        description="Number of currently active visitors in the store.",
        examples=[12],
    )
    total_visitors: int = Field(
        ...,
        ge=0,
        description="Total distinct visitors recorded since the start of the timeframe.",
        examples=[145],
    )
    average_dwell_time: float = Field(
        ...,
        ge=0.0,
        description="Average dwell time across all store zones in seconds.",
        examples=[45.2],
    )
    top_product: Optional[str] = Field(
        default=None,
        description="Shelf or product zone name with the highest engagement score.",
        examples=["Beverage Aisle"],
    )
    peak_hour: Optional[str] = Field(
        default=None,
        description="Hour with peak visitor traffic (formatted string, e.g., '14:00').",
        examples=["14:00"],
    )


class ProductRankingResponse(BaseModel):
    """Performance metrics and calculated rank score for a shelf/product zone."""

    model_config = ConfigDict(
        from_attributes=True,
        frozen=True,
    )

    product: str = Field(
        ...,
        min_length=1,
        description="Shelf or product zone name.",
        examples=["Beverage Aisle"],
    )
    customers: int = Field(
        ...,
        ge=0,
        description="Total distinct shoppers who engaged with this zone.",
        examples=[34],
    )
    avg_dwell_seconds: float = Field(
        ...,
        ge=0.0,
        description="Average dwell time per customer in seconds.",
        examples=[18.5],
    )
    score: float = Field(
        ...,
        ge=0.0,
        description="Calculated engagement score (customers * avg_dwell_seconds).",
        examples=[629.0],
    )


class HeatmapPointResponse(BaseModel):
    """Spatial coordinate point and dwell intensity for store heatmap rendering."""

    model_config = ConfigDict(
        from_attributes=True,
        frozen=True,
    )

    x: float = Field(
        ...,
        description="Normalized X spatial coordinate.",
        examples=[102.5],
    )
    y: float = Field(
        ...,
        description="Normalized Y spatial coordinate.",
        examples=[304.0],
    )
    value: float = Field(
        ...,
        ge=0.0,
        description="Accumulated dwell intensity value in seconds.",
        examples=[120.5],
    )


class TrafficAnalyticsResponse(BaseModel):
    """Hourly traffic aggregated metric."""

    model_config = ConfigDict(
        from_attributes=True,
        frozen=True,
    )

    hour: str = Field(
        ...,
        description="Formatted hour timestamp (e.g., 'YYYY-MM-DD HH:00:00' or 'HH:00').",
        examples=["2026-07-29 14:00:00"],
    )
    visitors: int = Field(
        ...,
        ge=0,
        description="Count of distinct visitors observed during this hour.",
        examples=[28],
    )

    @field_validator("hour", mode="before")
    @classmethod
    def serialize_hour_field(cls, value: Union[str, datetime]) -> str:
        """Ensures datetime objects returned from database date_trunc are stringified safely."""
        if isinstance(value, datetime):
            return value.strftime("%Y-%m-%d %H:%00:%00")
        return str(value)


class RecommendationResponse(BaseModel):
    """Actionable insight recommendation generated by analytics engine."""

    model_config = ConfigDict(
        from_attributes=True,
        frozen=True,
    )

    priority: str = Field(
        ...,
        description="Priority level of recommendation (e.g., 'High', 'Medium', 'Low').",
        examples=["High"],
    )
    message: str = Field(
        ...,
        min_length=1,
        description="Detailed actionable recommendation text.",
        examples=["Increase stock at Beverage Aisle due to high dwell time."],
    )


class ShelfAttentionResponse(BaseModel):
    """Detailed dwell and attention metrics mapped to a specific shelf."""

    model_config = ConfigDict(
        from_attributes=True,
        frozen=True,
    )

    shelf_name: str = Field(
        ...,
        min_length=1,
        description="Name of the shelf.",
        examples=["Electronics Display 1"],
    )
    total_dwell_seconds: float = Field(
        ...,
        ge=0.0,
        description="Total accumulated dwell duration across all shoppers in seconds.",
        examples=[1420.5],
    )
    customers: int = Field(
        ...,
        ge=0,
        description="Total distinct shoppers recorded at this shelf.",
        examples=[42],
    )
    avg_dwell_seconds: float = Field(
        ...,
        ge=0.0,
        description="Average dwell duration per shopper in seconds.",
        examples=[33.8],
    )