"""
Analytics API Router

Exposes analytics generated by the AnalyticsService to the React dashboard.
"""

from typing import Annotated

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.schemas.analytics_schema import (
    DashboardSummaryResponse,
    HeatmapPointResponse,
    ProductRankingResponse,
    RecommendationResponse,
    ShelfAttentionResponse,
    TrafficAnalyticsResponse,
)
from app.services.analytics_service import AnalyticsService

router = APIRouter(
    prefix="/api/analytics",
    tags=["Analytics"],
)

# ---------------------------------------------------------------------
# Dependencies
# ---------------------------------------------------------------------

# Remove default=24 from inside Query()
HoursQuery = Annotated[
    int,
    Query(
        ge=1,
        le=24 * 30,
        description="Analytics time window (hours).",
    ),
]


def get_analytics_service(
    db: Session = Depends(get_db),
) -> AnalyticsService:
    """Create an AnalyticsService instance."""
    return AnalyticsService(db)


AnalyticsDep = Annotated[
    AnalyticsService,
    Depends(get_analytics_service),
]

# ---------------------------------------------------------------------
# Analytics Endpoints
# ---------------------------------------------------------------------


@router.get("/summary", response_model=DashboardSummaryResponse)
def get_summary(
    service: AnalyticsDep,
    hours: HoursQuery = 24,  # <-- Set default value here using =
):
    return service.get_summary(hours)


@router.get("/products", response_model=list[ProductRankingResponse])
def get_products(
    service: AnalyticsDep,
    hours: HoursQuery = 24,  # <-- Set default value here using =
):
    return service.get_product_rankings(hours)


@router.get("/heatmap", response_model=list[HeatmapPointResponse])
def get_heatmap(
    service: AnalyticsDep,
    hours: HoursQuery = 24,  # <-- Set default value here using =
):
    return service.get_heatmap(hours)


@router.get("/traffic", response_model=list[TrafficAnalyticsResponse])
def get_traffic(
    service: AnalyticsDep,
    hours: HoursQuery = 24,  # <-- Set default value here using =
):
    return service.get_traffic(hours)


@router.get("/recommendations", response_model=list[RecommendationResponse])
def get_recommendations(
    service: AnalyticsDep,
    hours: HoursQuery = 24,  # <-- Set default value here using =
):
    return service.get_recommendations(hours)


@router.get("/attention", response_model=list[ShelfAttentionResponse])
def get_attention(
    service: AnalyticsDep,
    hours: HoursQuery = 24,  # <-- Set default value here using =
):
    """Return aggregated shelf tracking and dwell attention reports."""
    return service.get_shelf_attention(hours)