"""
Internal data structures for the Recommendation & Optimization Engine.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List, Dict, Any


class RecommendationCategory(str, Enum):
    """The 5 recommendation categories."""
    SHELF_OPTIMIZATION = "shelf_optimization"
    PRODUCT_PLACEMENT = "product_placement"
    PROMOTIONAL_PLACEMENT = "promotional_placement"
    CONSUMER_ENGAGEMENT = "consumer_engagement"
    LAYOUT_IMPROVEMENT = "layout_improvement"


class ImpactPriority(str, Enum):
    """Impact priority levels."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


@dataclass
class RecommendationItem:
    """A single actionable recommendation generated by AI engines."""
    id: str
    category: RecommendationCategory
    priority: ImpactPriority
    title: str
    description: str
    expected_revenue_lift_percent: float
    actionable_steps: List[str] = field(default_factory=list)
    target_product_or_zone: str = ""
    status: str = "pending"  # "pending" | "applied" | "dismissed"


@dataclass
class OptimizationSummaryData:
    """Summary metrics across generated optimization recommendations."""
    total_recommendations: int = 0
    high_priority_count: int = 0
    medium_priority_count: int = 0
    low_priority_count: int = 0
    projected_total_revenue_lift: float = 0.0
